services:
  webapi:
    container_name: Backend
    build:
      dockerfile: WebAPI/Dockerfile 
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
      
  client:
    container_name: Frontend
    build:
      context: ./ExchangeRateFront
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE_URL=http://webapi:8080
    volumes:
      - '.:/app'
      - '/app/node_modules'
    restart: always
    ports:
      - 80:80
    depends_on:
      - webapi
      
  db:
    container_name: Database
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - 1434:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "*FCg1y5wFPnZT8uk"
    volumes:
      - dbdata:/var/opt/mssql

volumes:
  dbdata: