# This is a generated file. Not intended for manual editing.
services:
  webapi:
    build:
      context: "C:\\Users\\1423d\\RiderProjects\\DeviconTest"
      dockerfile: "WebAPI/Dockerfile"
      target: "server-build"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/WebAPI.dll"
    environment: {}
    image: "webapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\1423d\\RiderProjects\\DeviconTest\\WebAPI:/app:rw"
    - "C:\\Users\\1423d\\RiderProjects\\DeviconTest:/src:rw"
    - "C:\\Users\\1423d\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
